nomeCliente = input("Digite o nome do cliente: ")
diaVencimento = input("Digite o dia de vencimento: ")
mesVencimento = input("Digite o mês de vencimento: ")
valorFatura = input("Digite o valor da fatura: ")
print()
print("Olá, ", nomeCliente)
print("A sua fatura com vencimento em", diaVencimento, mesVencimento, "no valor de", valorFatura, "está fechada.")
